### ISSUE TITLE
Reconocimientos 2019

### ISSUE THREAD

**Issue by danielcarranza** [datauy/atuservicio#53]
- [x] Pasar datos a tabla
- [x] Datos recibidos
- [x] Subidos a staging
- [x] Invertir orden, 2019 arriba, 2018 abajo
- [x] ponerle "target: _blank" a los enlaces de los PDF
- [x] OK en staging

Va CSV actualizado, igual lo puse como commit también

[recognitions.zip](https://github.com/datauy/atuservicio/files/4103291/recognitions.zip)

**Comment by picandocodigo** [comment]
@danielcarranza Dales una revisada en staging pero creo que están :ok:

**Comment by danielcarranza** [comment]
Lujo, se lo mando a Jorge para OK

**Comment by danielcarranza** [comment]
Miento @picandocodigo, les faltan los enlaces a los PDF (o subir los PDF quizás)

**Comment by picandocodigo** [comment]
Ah, buen punto!

**Comment by picandocodigo** [comment]
Lo peor es que antes de hacer los cambios para los reconocimientos nuevos pensé "Ah, faltan los PDF". Después se me olvidó y pensé que ya estaba :laughing:

**Comment by danielcarranza** [comment]
Supuse que era subirlos nomás

**Comment by danielcarranza** [comment]
@picandocodigo Me pide Jorge invertir el orden en que se muestran, primero 2019, después 2018.
Perdón que creo que me lo había dicho y me lo comí.

Si es simplemente cambiar el orden en el CSV, confírmamela y me encargo yo.

**Comment by picandocodigo** [comment]
Me fijo después para cambiarlo en el código que los ordene descendiente por año.

**Comment by picandocodigo** [comment]
Quedó lo del orden, falta que manden los PDF

**Comment by danielcarranza** [comment]
Los PDF están en el ZIP que está subido a este issue

**Comment by danielcarranza** [comment]
No, perdón eso es el CSV
Pero ya lo subo

**Comment by danielcarranza** [comment]
[PDF.zip](https://github.com/datauy/atuservicio/files/4130109/PDF.zip)

**Comment by picandocodigo** [comment]
Quedó bo!

**Comment by danielcarranza** [comment]
👍

**Comment by danielcarranza** [comment]
Volvieron a quedar ordenados 2018-2019 en producción... 🤷‍♂️

**Comment by picandocodigo** [comment]
Se puede cerrar, ¿no?

**Comment by danielcarranza** [comment]
Si, no sé porqué no lo hice...
