### ISSUE TITLE
Solicitud de consulta y tiempos de espera

### ISSUE THREAD

**Issue by danielcarranza** [datauy/atuservicio#54]
- [x] Datos recibidos
- [x] Subidos a staging
- [x] Resubir datos corregidos
- [x] Corregir en solicitud de consulta datos "corridos" una columna
- [x] OK en staging

**Comment by danielcarranza** [comment]
Mandó correo Jorge, los datos tenían un error, hay que resubirlos...

[Solicitud de Consultas dic 2019.csv.zip](https://github.com/datauy/atuservicio/files/4122849/Solicitud.de.Consultas.dic.2019.csv.zip)

**Comment by picandocodigo** [comment]
Ya quedó levantado en staging esto
