### ISSUE TITLE
Estructura básica

### ISSUE THREAD

**Issue by danielcarranza** [datauy/atuservicio#56]
[estructura basica 2020.csv.zip](https://github.com/datauy/atuservicio/files/4122852/estructura.basica.2020.csv.zip)

[estructura generalold.csv.zip](https://github.com/datauy/atuservicio/files/4136191/estructura.generalold.csv.zip)

Se agrega un nuevo campo **en el comparador**: "Servicios de atención para adolescentes que implementan estándares nacionales de calidad de atención" (es un campo si/no, que se representa con el tick/cruz).

- [X] Datos recibidos
- [x] Agregar campo en comparador
- [x] Cargar datos en staging
- [x] Cargar datos actualizados de sedes
- [x] Se corre hace ala derecha la columna cuando "no hay datos"
- [x] Cambia de nombre "Disponibilidad de Espacios específicos para atención a adolescentes" a "**Disponibilidad de servicios de atención para adolescentes**"
- [x] OK en staging
- [x] Carga de nuevos datos de sedes (sin servicios)

**Comment by picandocodigo** [comment]
Ya está esto en staging:

![image](https://user-images.githubusercontent.com/689327/73295599-e0128f00-41ff-11ea-95a7-30d6436c0b99.png)

**Comment by picandocodigo** [comment]
Listo

**Comment by danielcarranza** [comment]
Gravias

**Comment by picandocodigo** [comment]
:bomb:

**Comment by danielcarranza** [comment]
JAJAJAJAJAJAJAJAJAJAJAJA
