### ISSUE TITLE
Indicadores asistenciales

### ISSUE THREAD

**Issue by danielcarranza** [datauy/atuservicio#57]
[Indicadores asistenciales 2020.csv.zip](https://github.com/datauy/atuservicio/files/4122882/Indicadores.asistenciales.2020.csv.zip)

Cambia el nombre del campo "Indice de cesareas SIP 2017" por "Tasa de cesáreas"

- [x] Datos recibidos
- [x] Cambiar nombre de campo a "Tasa de cesáreas" en home
- [x] Cambiar nombre de campo a "Tasa de cesáreas" en comprador
- [x] Cargar datos
- [x] Corregir en "Porcentaje de médicos con capacitación realizada en tratamiento del infarto agudo de miocardio con ST elevado" que los datos "N/C" aparezcan como "N/C" y no  0%. (Ver MP 9508)
![Captura de Pantalla 2020-01-29 a la(s) 15 50 01](https://user-images.githubusercontent.com/1755382/73388377-df860100-42b0-11ea-8c9a-603ef54486fa.png)
- [x] Corregir en home, que los precios gratis de ASSE aparecen con cara triste en vez de contenta
![Captura de Pantalla 2020-01-29 a la(s) 16 01 38](https://user-images.githubusercontent.com/1755382/73388514-2116ac00-42b1-11ea-83f9-8d458c2d3a4a.png)
- [x] Corregir nombre de dato en home y comparador: "**Porcentaje de embarazadas con control de HIV y VDRL en el 1er, 2do y 3er trimestre**" (le falta 2do ene lo que está)
- [x] Corregir nombre de dato en home y comparador: **"Porcentaje de usuarios de 25 a 64 años captados e identificados como hipertensos"** (mal escrito "captados" en lo que está)
- [x] OK en staging

**Comment by picandocodigo** [comment]
Quedó esto en staging también

**Comment by danielcarranza** [comment]
Puta que me parió, me faltó el tilde en "Índice", en ambos casos (home y comparador) me lo asigno y corrijo yo.

**Comment by danielcarranza** [comment]
Va con nombre "Tasa" al final. Lo cambio yo igual.

**Comment by danielcarranza** [comment]
Perdón @picandocodigo pero no encontré dónde cambiar los nombres de los títulos de datos que están como "Indice de cesáreas" y hay que pasar a "Tasa de cesáreas" tanto en home como comparador, ¿me podrás ayudar?

**Comment by picandocodigo** [comment]
Ah, eso está en el código en una configuración de metadatos. Lo cambio!

**Comment by picandocodigo** [comment]
¡Quedó!

**Comment by danielcarranza** [comment]
Gracias

**Comment by picandocodigo** [comment]
Esto creo que está todo en staging, pero dale una revisada por las dudas

**Comment by danielcarranza** [comment]
Está todo, gracias
