### ISSUE TITLE
Recursos Humanos

### ISSUE THREAD

**Issue by danielcarranza** [datauy/atuservicio#58]
[Atuservicio 2020 RRHH.csv.zip](https://github.com/datauy/atuservicio/files/4122893/Atuservicio.2020.RRHH.csv.zip)

Hay cambios de nombres de campos **en el comparador**: 
- [x] "Medicina General Cantidad de CAD" pasa a ser "**Cantidad de CAD de Medicina General**"
- [x] "Medicina Familiar Cantidad de CAD" pasa a ser "**Cantidad de CAD de Medicina Familiar**"
- [x] "Pediatría Cantidad de CAD" pasa a ser "**Cantidad de CAD de Pediatría**"
- [x] "Ginecotología Cantidad de CAD" pasa a ser "**Cantidad de CAD de Ginecotología**"
- [x] "Medicina Interna Cantidad de CAD" pasa a ser "**Cantidad de CAD de Medicina Interna**"
- [x] "Medicina Intensiva de Adultos Cantidad de CAD" pasa a ser "**Cantidad de CAD de Medicina Intensiva de Adultos**"
- [x] "Medicina Intensiva Pediátrica Cantidad de CAD" pasa a ser "**Cantidad de CAD de Medicina Intensiva Pediátrica**"
- [x] "Neonatología Cantidad de CAD" pasa a ser "**Cantidad de CAD de Neonatología**"
- [x] "Psiquiatría Adultos Cantidad de CAD" pasa a ser "**Cantidad de CAD de Psiquiatría Adultos**"
- [x] "Psiquiatría Pediátrica Cantidad de CAD" pasa a ser "**Cantidad de CAD de Psiquiatría Pediátrica**"
- [x] "Especialidades Médicas Cantidad de CAD" pasa a ser "**Cantidad de CAD de Especialidades Médicas**"
- [x] "Cirugía General Cantidad de CAD" pasa a ser "**Cantidad de CAD de Cirugía General**"
- [x] "Medicina de Emergencia Adultos Cantidad de CAD" pasa a ser "**Cantidad de CAD de Medicina de Emergencia Adultos**"
- [x] "Medicina de Emergencia Pediátrica Cantidad de CAD" pasa a ser "**Cantidad de CAD de Medicina de Emergencia Pediátrica**"
- [x] "Proporción de trabajadores que realizaron el seminario de capacitación en el 2017" pasa a ser "**Proporción de trabajadores que realizaron el seminario de capacitación en el 2019**"

Por otro lado, se agregan datos nuevos **en el comparador** (van antes de "Proporción de trabajadores que realizaron el seminario de capacitación en el 2019"):
- Cantidad de CAD de Medicina Rural
- Cantidad de CAD de Imagenología
- Cantidad de CAD de Anestesia

El de Medicina Rural y Anestesiología, sólo tienen datos para ASSE, en todos los demás prestadores dice "no corresponde". Idealmente, **estaría genial sólo mostrarlos en ASSE**.

- [x] Datos recibidos
- [x] Cambios de nombre en comparador
- [x] Agregar datos nuevos en comparador
- [x] En "Cantidad de CAD de Imagenología" de los prestadores privados, aparece "No corresponde", en lugar de "0". Quizás sea un error introducido por el "NO corresponded" para MP.
- [x] OK en staging

**Comment by picandocodigo** [comment]
Está corriendo el importador en este momento en staging y cuando termine debería estar todo lo de este ticket :crossed_fingers:

**Comment by danielcarranza** [comment]
Revisanding...

**Comment by danielcarranza** [comment]
Brillante, mando a revisar

**Comment by danielcarranza** [comment]
Agregué un problema con "Cantidad de CAD Imagenología" en los privados
