### ISSUE TITLE
Actualizaciones textos "i"

### ISSUE THREAD

**Issue by danielcarranza** [datauy/atuservicio#59]
**En home**
- [x] Estructura
- [x] Tiempos de espera
- [x] Derechos de usuario
- [x] Precios
- [x] Indicadores asistenciales
- [x] Cantidad de usuarios
- [x] RRHH

**En comparador**
- [x] Reconocimientos
- [x] Agregar link a la "i" de reconocimientos (reconocimientos_modal)
- [x] Estructura
- [x] Tiempos de espera
- [x] Derechos de usuario
- [x] Precios
- [x] Indicadores Asistenciales (ídem home)
- [ ] ¿Sedes?

"¿?" = Consultando con Ida

**Comment by danielcarranza** [comment]
@picandocodigo 

Pidieron modal para reconocimientos que no existía, así que al principio de https://github.com/datauy/atuservicio/edit/master/app/views/compare/_modals.html.erb
copié y pegué el div de  y le puse .
Le puse c de id. Habría que ponerle el link a esa "i" para que ande.

Si ves eso ok, aprobate estos commit para cerrar:

Textos "i" home: d3a37a5cb4313f1f9a7718daa6a7f94e7ad101e0
Textos "i" especiales ASSE: 47660413c9dee196b8615ff3435bbfa957845b6f
Textos "i" comparador: 3df51b2f1659dbe926a1529b2ba68a732464d434

**Comment by picandocodigo** [comment]
A ver cómo 🤬 se hacía esto de los modales... 😆

**Comment by picandocodigo** [comment]
Quedó en staging :+1:
