### ISSUE TITLE
Revisión de evaluación técnica.

### ISSUE THREAD

**Issue by mariajosegomezcampos** [datauy/ATuServicio#73]
Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID.

# Issue de evaluación técnica:

Al haber contrastado la información presentadas en el repo oficial con los campos solicitados en la plantilla de README.md hemos encontrado los siguiente puntos a mejorar:
-  [x]  Agregar el microservicio de reportes de evaluación estática de código de Sonarcloud, teniendo en cuenta que las condiciones ideales de los reportes son:

1. Ausencia de fallos estructurales.
1. Menos del 25% de líneas duplicadas.
1. Menos de 10 problemas críticos.
1. Más del 50% de clases, interfaces y métodos documentados.
1. Deuda técnica menor a 30 días.
1. Cobertura de test más del 25%.

-  [x]  Agregar el badge de este servicio visible en el readme.md
 -  [ ] Agregar el microservicio de integración continua de código (opcional)
-  [ ] Agregar el badge de este servicio visible en el readme.md (opcional)

**Comment by danielcarranza** [comment]
[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=datauy_ATuServicio&metric=alert_status)](https://sonarcloud.io/dashboard?id=datauy_ATuServicio)

**Comment by knlopenknowledge** [comment]
Hola @danielcarranza muchas gracias por todo el trabajo en la piloto, estoy revisando que para pasar a publicar esta herramienta en code.iadb.org estaría faltando agregar el badge de Quality gate passed de Sonarcloud en el readme.md. Con esto, los puntos que levantó @mariajosegomezcampos  quedarían cerrados. Quedamos super atentos a cualquier duda o consulta para poder cerrar este issue de evaluación técnica y pasar a publicar la herramienta en nuestro catálogo.

**Comment by danielcarranza** [comment]
Listo @knlopenknowledge
